### ISSUE TITLE
Incorrect offsets (?)

### ISSUE THREAD

**Issue by Iraq1337** [10HEAD/ValorantOffsets#12]
the offsets of bone_array & bone_count seem to be invalid.
valid bone_array should be: 0x5c0 (afaik)
valid bone_count should be: 0x5c8 (afaik)

**Comment by Pinguu-dev** [comment]
Updated, for your team id point that you removed - The Team ID offset is still the same.

**Comment by Iraq1337** [comment]
removed due to me realizing that.
